name = "hartmann-crm-api"
main = "worker.js"
compatibility_date = "2026-10-01"
workers_dev = true
preview_urls = false

[vars]
GITHUB_OWNER = "Suzana991"
GITHUB_REPO = "hartmann-crm"
GITHUB_BRANCH = "data"
DATA_PATH = "data.json"
CHANGE_PATH = "changelog.json"
CHAT_PATH = "chat.json"
CORS_ORIGIN = "https://suzana991.github.io"
